"""ARCH-D drawing sheets, drawn from the model rather than illustrated beside it.

Every sheet here is generated by reading the authored IFC — column positions, wall runs, space
polygons, grid spacing — so a sheet cannot drift from the model it documents. That is the whole
argument for generating them: a drawing produced by hand next to a model is a second source of truth
and will disagree with the first one eventually.

Output is SVG at ARCH-D (36 x 24 in / 914.4 x 609.6 mm), with a title block, graphic scale, north
arrow and a stated drawing status. Five sheets per project:

    G0.01   Cover sheet and project data
    A1.01   Overall floor plan, Level 1
    A2.01   Building elevations
    S2.01   Framing plan, typical level
    E2.01   Power and lighting plan, typical level
"""
from __future__ import annotations

import datetime as dt
import html

import projectdata as P

SHEET_W, SHEET_H = 914.4, 609.6         # ARCH-D, millimetres
MARGIN = 12.0
TB_X = 724.4                            # title-block divider
DRAW_W = TB_X - MARGIN * 2              # usable drawing width
INK = "#111"
THIN = "#555"
FAINT = "#999"
GRID = "#bbb"


def _esc(s) -> str:
    return html.escape(str(s), quote=True)


class Sheet:
    """An ARCH-D sheet. Coordinates are millimetres on the sheet."""

    def __init__(self, spec: dict, number: str, title: str, discipline: str):
        self.spec = spec
        self.number = number
        self.title = title
        self.discipline = discipline
        self.body: list[str] = []

    # ── primitives ───────────────────────────────────────────────────────────────────────────────
    def line(self, x1, y1, x2, y2, stroke=INK, w=0.3, dash=None):
        d = f' stroke-dasharray="{dash}"' if dash else ""
        self.body.append(f'<line x1="{x1:.2f}" y1="{y1:.2f}" x2="{x2:.2f}" y2="{y2:.2f}" '
                         f'stroke="{stroke}" stroke-width="{w}"{d}/>')

    def rect(self, x, y, w, h, stroke=INK, fill="none", sw=0.3, dash=None):
        d = f' stroke-dasharray="{dash}"' if dash else ""
        self.body.append(f'<rect x="{x:.2f}" y="{y:.2f}" width="{w:.2f}" height="{h:.2f}" '
                         f'fill="{fill}" stroke="{stroke}" stroke-width="{sw}"{d}/>')

    def circle(self, cx, cy, r, stroke=INK, fill="none", sw=0.3):
        self.body.append(f'<circle cx="{cx:.2f}" cy="{cy:.2f}" r="{r:.2f}" fill="{fill}" '
                         f'stroke="{stroke}" stroke-width="{sw}"/>')

    def text(self, x, y, s, size=3.0, anchor="start", fill=INK, bold=False):
        self.body.append(
            f'<text x="{x:.2f}" y="{y:.2f}" font-size="{size}" text-anchor="{anchor}" '
            f'fill="{fill}" font-weight="{"bold" if bold else "normal"}" '
            f'font-family="Helvetica,Arial,sans-serif">{_esc(s)}</text>')

    def panel(self, x, y, w, h):
        """An opaque backing panel. The plan is fitted to fill the sheet, so title and legend blocks
        sit over it; without this they read as text tangled in the drawing."""
        self.body.append(f'<rect x="{x:.2f}" y="{y:.2f}" width="{w:.2f}" height="{h:.2f}" '
                         f'fill="#ffffff" fill-opacity="0.92" stroke="{GRID}" stroke-width="0.25"/>')

    def poly(self, pts, stroke=INK, fill="none", sw=0.3):
        d = " ".join(f"{x:.2f},{y:.2f}" for x, y in pts)
        self.body.append(f'<polygon points="{d}" fill="{fill}" stroke="{stroke}" '
                         f'stroke-width="{sw}"/>')

    # ── sheet furniture ──────────────────────────────────────────────────────────────────────────
    def title_block(self, scale_note: str = ""):
        s = self.spec
        self.rect(MARGIN, MARGIN, SHEET_W - MARGIN * 2, SHEET_H - MARGIN * 2, INK, "none", 1.0)
        self.line(TB_X, MARGIN, TB_X, SHEET_H - MARGIN, INK, 0.8)
        x = TB_X + 6
        self.text(x, 32, s["name"].upper(), 6.2, bold=True)
        self.text(x, 42, f'{s["subtype"].upper()} · SAMPLE PROJECT', 3.2, fill=THIN)
        self.line(x, 48, SHEET_W - MARGIN - 6, 48, INK, 0.4)

        rows = [
            ("PROJECT NO.", f'MSL-{s["key"][:6].upper()}'),
            ("SECTOR", s["sector"]),
            ("GROSS AREA", f'{s["gross_sf"]:,} sf'),
            ("STOREYS", str(s["storeys"])),
            ("STRUCTURE", s["structure"].title()),
            ("DISCIPLINE", self.discipline),
            ("SCALE", scale_note or "AS NOTED"),
            ("DATE", f"{dt.date.today():%d %b %Y}".upper()),
            ("ISSUE", "A — DESIGN DEVELOPMENT"),
        ]
        y = 60
        for label, val in rows:
            self.text(x, y, label, 2.5, fill=FAINT, bold=True)
            self.text(x, y + 4.6, val, 3.4)
            y += 12.5

        # The status note. A sample sheet that does not say what it is invites being cited as
        # something it is not.
        y += 4
        self.line(x, y, SHEET_W - MARGIN - 6, y, INK, 0.4)
        y += 8
        self.text(x, y, "NOT FOR CONSTRUCTION", 4.6, bold=True)
        for i, ln in enumerate([
                "Synthetic sample project. Generated from",
                "tools/sectors.py by tools/sheets.py. No",
                "part of this has been reviewed or sealed by",
                "a licensed professional, and no dimension",
                "has been verified against a built condition.",
                "Do not use to build, bid, or price."]):
            self.text(x, y + 7 + i * 4.4, ln, 2.7, fill=THIN)

        # Sheet number, bottom right — the thing people look for first.
        self.line(x, SHEET_H - MARGIN - 34, SHEET_W - MARGIN - 6, SHEET_H - MARGIN - 34, INK, 0.4)
        self.text(x, SHEET_H - MARGIN - 24, self.title.upper(), 3.4, bold=True)
        self.text(x, SHEET_H - MARGIN - 8, self.number, 11.0, bold=True)

    def north_arrow(self, cx, cy, r=7.0):
        self.circle(cx, cy, r, INK, "none", 0.4)
        self.poly([(cx, cy - r + 1), (cx - 2.6, cy + r - 2.5), (cx, cy + r - 4.5),
                   (cx + 2.6, cy + r - 2.5)], INK, INK, 0.3)
        self.text(cx, cy - r - 2, "N", 3.4, anchor="middle", bold=True)

    def scale_bar(self, x, y, mm_per_m: float, metres=(0, 5, 10, 20)):
        """A graphic scale, because a printed sheet's stated scale is only true at one paper size."""
        self.line(x, y, x + metres[-1] * mm_per_m, y, INK, 0.5)
        for m in metres:
            xx = x + m * mm_per_m
            self.line(xx, y - 1.8, xx, y + 1.8, INK, 0.5)
            self.text(xx, y + 6, str(m), 2.6, anchor="middle")
        self.text(x + metres[-1] * mm_per_m / 2, y - 4, "METRES", 2.4, anchor="middle", fill=THIN)

    # ── output ───────────────────────────────────────────────────────────────────────────────────
    def render(self) -> str:
        return (f'<svg xmlns="http://www.w3.org/2000/svg" width="{SHEET_W}mm" '
                f'height="{SHEET_H}mm" viewBox="0 0 {SHEET_W} {SHEET_H}">'
                f'<rect x="0" y="0" width="{SHEET_W}" height="{SHEET_H}" fill="#fff"/>'
                + "".join(self.body) + "</svg>")


# ─────────────────────────────────────────────────────────────────────────────────────────────────
# Plan fitting
# ─────────────────────────────────────────────────────────────────────────────────────────────────
#: Annotation gutters, in SHEET millimetres. Grid bubbles, dimension strings and level tags are a
#: fixed size on paper no matter how big the building is, so the space they need is reserved in
#: millimetres. Expressing them in building metres — which an earlier version did — meant a 70 m
#: residential block pushed its own dimension line 89 mm off the left edge of the sheet, because a
#: 14 m offset scales with the plan and the text does not.
GUTTER_L, GUTTER_R, GUTTER_T, GUTTER_B = 34.0, 12.0, 24.0, 30.0


class Fit:
    """Maps building metres to sheet millimetres, centred in the drawing area, with the annotation
    gutters reserved so nothing lands off the sheet."""

    def __init__(self, spec: dict, pad: float = 14.0):
        w, d = spec["footprint"]
        avail_w = DRAW_W - pad * 2 - GUTTER_L - GUTTER_R
        avail_h = SHEET_H - MARGIN * 2 - pad * 2 - GUTTER_T - GUTTER_B
        self.k = min(avail_w / w, avail_h / d)
        left = MARGIN + pad + GUTTER_L
        top = MARGIN + pad + GUTTER_T
        self.ox = left + (avail_w - w * self.k) / 2
        self.oy = top + (avail_h + d * self.k) / 2            # flip Y: north up

    def x(self, mx: float) -> float:
        return self.ox + mx * self.k

    def y(self, my: float) -> float:
        return self.oy - my * self.k

    @property
    def ratio(self) -> str:
        """The true drawn ratio, e.g. 1:250."""
        return f"1:{round(1000 / self.k / 5) * 5}"


def _grid(spec):
    import geometry as G
    return G.grid_lines(spec)


def _draw_grid(sh: Sheet, fit: Fit, spec: dict):
    """Grid lines with bubbles. Bubble offsets are millimetres off the building edge, not metres."""
    xs, ys = _grid(spec)
    w, d = spec["footprint"]
    bub_y = fit.y(d) - 13.0          # 13 mm above the top of the plan
    bub_x = fit.x(0) - 13.0          # 13 mm left of it
    for i, x in enumerate(xs):
        sh.line(fit.x(x), fit.y(d) - 8.0, fit.x(x), fit.y(0) + 6.0, GRID, 0.2, "2,1.5")
        sh.circle(fit.x(x), bub_y, 3.4, THIN, "#fff", 0.3)
        sh.text(fit.x(x), bub_y + 1.2, chr(65 + i % 26), 2.8, "middle", THIN, True)
    for j, y in enumerate(ys):
        sh.line(fit.x(0) - 8.0, fit.y(y), fit.x(w) + 6.0, fit.y(y), GRID, 0.2, "2,1.5")
        sh.circle(bub_x, fit.y(y), 3.4, THIN, "#fff", 0.3)
        sh.text(bub_x, fit.y(y) + 1.2, str(j + 1), 2.8, "middle", THIN, True)


def _dim_string(sh: Sheet, fit: Fit, spec: dict):
    w, d = spec["footprint"]
    yy = fit.y(0) + 18.0             # 18 mm below the plan
    sh.line(fit.x(0), yy, fit.x(w), yy, INK, 0.3)
    for xx in (0, w):
        sh.line(fit.x(xx), yy - 2, fit.x(xx), yy + 2, INK, 0.3)
    sh.text(fit.x(w / 2), yy - 2.5, f"{w:.1f} m  ({w * 3.28084:.0f} ft)", 2.8, "middle")
    xx = fit.x(0) - 24.0             # 24 mm left of the plan
    sh.line(xx, fit.y(0), xx, fit.y(d), INK, 0.3)
    for yv in (0, d):
        sh.line(xx - 2, fit.y(yv), xx + 2, fit.y(yv), INK, 0.3)
    sh.text(xx - 3, fit.y(d / 2), f"{d:.1f} m  ({d * 3.28084:.0f} ft)", 2.8, "end")


# ─────────────────────────────────────────────────────────────────────────────────────────────────
# The sheets
# ─────────────────────────────────────────────────────────────────────────────────────────────────
def cover_sheet(spec: dict, model: dict, registers: dict) -> Sheet:
    sh = Sheet(spec, "G0.01", "Cover Sheet and Project Data", "General")
    sh.title_block("NTS")
    x0, y0 = MARGIN + 18, MARGIN + 34

    sh.text(x0, y0, spec["name"].upper(), 13.0, bold=True)
    sh.text(x0, y0 + 10, spec["subtype"], 5.0, fill=THIN)
    sh.line(x0, y0 + 16, TB_X - 18, y0 + 16, INK, 0.6)

    # Summary paragraph, wrapped by hand because SVG will not do it.
    words, line, lines = spec["summary"].split(), "", []
    for word in words:
        if len(line) + len(word) > 96:
            lines.append(line); line = word
        else:
            line = f"{line} {word}".strip()
    lines.append(line)
    for i, ln in enumerate(lines):
        sh.text(x0, y0 + 26 + i * 5.2, ln, 3.6)

    yy = y0 + 30 + len(lines) * 5.2
    pf = P.proforma(spec)
    bt = P.budget_totals(spec)
    start, finish = P.schedule_span(spec)
    cost_exp, days_exp = registers["risk_exposure"]

    blocks = [
        ("PROJECT DATA", [
            ("Gross building area", f'{spec["gross_sf"]:,} sf'),
            ("Net rentable / usable", f'{pf["nra"]:,} sf  ({spec["efficiency"]:.0%})'),
            ("Storeys", f'{spec["storeys"]} @ {spec["storey_height"]:.2f} m'),
            ("Footprint", f'{spec["footprint"][0]:.1f} × {spec["footprint"][1]:.1f} m'),
            ("Structural system", spec["structure"].title()),
            ("Envelope", spec["envelope"]),
        ]),
        ("MODEL", [
            ("Elements", f'{model["elements"]:,}'),
            ("IFC classes", str(len([c for c in model["classes"] if c.startswith("Ifc")]))),
            ("Spaces", f'{model["classes"].get("IfcSpace", 0)}'),
            ("LOD claim", spec["lod"][:44]),
            ("Schema", "IFC4"),
        ]),
        ("COST AND PROGRAMME", [
            ("Revised budget", f'${bt["revised"]:,.0f}'),
            ("Forecast at completion", f'${bt["forecast"]:,.0f}'),
            ("Total development cost", f'${pf["total_cost"]:,.0f}'),
            ("Cost per gross sf", f'${pf["cost_psf"]:,.0f}'),
            ("Construction start", f"{start:%d %b %Y}"),
            ("Substantial completion", f"{finish:%d %b %Y}"),
        ]),
        ("REGISTERS", [
            ("Sheets in set", f'{registers["sheets"]} ({registers["issued"]} issued)'),
            ("Approvals tracked", str(registers["permits"])),
            ("Risks open", f'{registers["risks"]}  (${cost_exp:,.0f} / {days_exp} d exposure)'),
            ("Long-lead packages", str(registers["procurement"])),
            ("Phase gates", str(registers["phases"])),
        ]),
    ]
    col_w = (TB_X - 18 - x0) / 2
    for i, (heading, items) in enumerate(blocks):
        cx = x0 + (i % 2) * col_w
        cy = yy + (i // 2) * 108
        sh.text(cx, cy, heading, 3.4, fill=FAINT, bold=True)
        sh.line(cx, cy + 2.5, cx + col_w - 14, cy + 2.5, THIN, 0.3)
        for j, (k, v) in enumerate(items):
            sh.text(cx, cy + 10 + j * 6.4, k, 3.0, fill=THIN)
            sh.text(cx + col_w - 16, cy + 10 + j * 6.4, v, 3.0, anchor="end", bold=True)
    return sh


def floor_plan(spec: dict, geo: dict) -> Sheet:
    sh = Sheet(spec, "A1.01", "Overall Floor Plan — Level 1", "Architectural")
    fit = Fit(spec)
    sh.title_block(fit.ratio)
    _draw_grid(sh, fit, spec)

    # Spaces first, so structure reads on top of them.
    for sp in geo["spaces"]:
        x, y, w, d = sp["x"], sp["y"], sp["w"], sp["d"]
        sh.rect(fit.x(x), fit.y(y + d), w * fit.k, d * fit.k, "#c8d4e0", "#eef3f8", 0.25)
        cx, cy = fit.x(x + w / 2), fit.y(y + d / 2)
        sh.text(cx, cy, sp["name"], 2.8, "middle", THIN, True)
        sh.text(cx, cy + 4.2, f'{sp["area_sf"]:,.0f} sf', 2.5, "middle", FAINT)

    # Walls as their real footprint rectangles.
    for wl in geo["walls"]:
        (ax, ay), (bx, by) = wl["start"], wl["end"]
        sh.line(fit.x(ax), fit.y(ay), fit.x(bx), fit.y(by), INK, max(0.6, wl["thickness"] * fit.k))

    # Columns.
    for c in geo["columns"]:
        s = max(1.2, 0.55 * fit.k)
        sh.rect(fit.x(c["x"]) - s / 2, fit.y(c["y"]) - s / 2, s, s, INK, INK, 0.2)

    # Doors, as swing marks on the plan.
    for dr in geo["doors"]:
        sh.circle(fit.x(dr["x"]), fit.y(dr["y"]), 1.6, "#b04a2f", "#fff", 0.4)

    _dim_string(sh, fit, spec)
    sh.panel(MARGIN + 4, MARGIN + 4, 132, 20)
    sh.text(MARGIN + 8, MARGIN + 13, "LEVEL 1 FLOOR PLAN", 5.0, bold=True)
    sh.text(MARGIN + 8, MARGIN + 20, f"SCALE {fit.ratio} AT ARCH-D", 2.8, fill=THIN)
    sh.north_arrow(TB_X - 26, MARGIN + 20)
    sh.panel(MARGIN + 4, SHEET_H - MARGIN - 26, 92, 22)
    sh.scale_bar(MARGIN + 12, SHEET_H - MARGIN - 12, fit.k)
    return sh


def elevations(spec: dict, geo: dict) -> Sheet:
    sh = Sheet(spec, "A2.01", "Building Elevations", "Architectural")
    w, d = spec["footprint"]
    h = spec["storey_height"] * spec["storeys"]
    pad = 26.0
    avail_w = DRAW_W - pad * 2
    k = min(avail_w / max(w, d), (SHEET_H - MARGIN * 2 - 150) / h / 2)
    sh.title_block(f"1:{round(1000 / k / 5) * 5}")

    for idx, (label, length) in enumerate((("SOUTH ELEVATION", w), ("EAST ELEVATION", d))):
        ox = MARGIN + pad + (avail_w - length * k) / 2
        oy = MARGIN + 70 + idx * (h * k + 78)
        # Ground line
        sh.line(ox - 14, oy + h * k, ox + length * k + 14, oy + h * k, INK, 0.8)
        # Envelope
        sh.rect(ox, oy, length * k, h * k, INK, "#f6f7f9", 0.5)
        # Storey lines and level tags
        for i in range(spec["storeys"] + 1):
            yy = oy + h * k - i * spec["storey_height"] * k
            sh.line(ox - 10, yy, ox + length * k + 10, yy, THIN if i else INK, 0.25 if i else 0.5,
                    "2,1.5" if i else None)
            sh.text(ox - 12, yy - 1.2, f'L{i + 1}' if i < spec["storeys"] else "ROOF",
                    2.5, "end", THIN)
            sh.text(ox + length * k + 12, yy - 1.2,
                    f'+{i * spec["storey_height"]:.2f}', 2.5, "start", FAINT)
        # Openings, read from the model: windows on this elevation, banded per storey
        if spec["envelope"] == "curtainwall":
            step = max(1.5, length / 26)
            xx = ox + step
            while xx < ox + length * k - step:
                sh.line(xx, oy + 1, xx, oy + h * k - 1, THIN, 0.2)
                xx += step
            for i in range(1, spec["storeys"]):
                yy = oy + h * k - i * spec["storey_height"] * k
                sh.line(ox + 1, yy, ox + length * k - 1, yy, THIN, 0.2)
        else:
            n = max(3, int(length // 6))
            for i in range(spec["storeys"]):
                yy = oy + h * k - (i + 1) * spec["storey_height"] * k
                for j in range(n):
                    wx = ox + (j + 0.5) / n * length * k - 0.75 * k
                    sh.rect(wx, yy + 0.55 * k, 1.5 * k, 1.5 * k, INK, "#dde5ee", 0.25)
        sh.text(ox, oy - 8, label, 4.6, bold=True)
        sh.text(ox, oy - 3, f"{length:.1f} m long · {h:.2f} m to roof", 2.8, fill=THIN)

    sh.scale_bar(MARGIN + 22, SHEET_H - MARGIN - 18, k)
    return sh


def framing_plan(spec: dict, geo: dict) -> Sheet:
    sh = Sheet(spec, "S2.01", "Framing Plan — Typical Level", "Structural")
    fit = Fit(spec)
    sh.title_block(fit.ratio)
    _draw_grid(sh, fit, spec)

    for b in geo["beams"]:
        (ax, ay), (bx, by) = b["start"], b["end"]
        sh.line(fit.x(ax), fit.y(ay), fit.x(bx), fit.y(by), INK, 0.7)
    for c in geo["columns"]:
        s = max(1.6, 0.55 * fit.k)
        sh.rect(fit.x(c["x"]) - s / 2, fit.y(c["y"]) - s / 2, s, s, INK, INK, 0.2)

    _dim_string(sh, fit, spec)
    sh.panel(MARGIN + 4, MARGIN + 4, 132, 14)
    sh.text(MARGIN + 8, MARGIN + 13, "TYPICAL FRAMING PLAN", 5.0, bold=True)
    sh.north_arrow(TB_X - 26, MARGIN + 20)

    # A member schedule that states the sections actually used, read from the model.
    n = len(geo["sections"])
    lx, ly = MARGIN + 4, SHEET_H - MARGIN - 34 - n * 4.6
    sh.panel(lx, ly - 6, 96, 32 + n * 4.6)
    sh.text(lx + 4, ly, "MEMBER SCHEDULE", 3.0, fill=FAINT, bold=True)
    for i, (k, v) in enumerate(sorted(geo["sections"].items())):
        sh.text(lx + 4, ly + 6 + i * 4.6, f"{k}", 2.8)
        sh.text(lx + 88, ly + 6 + i * 4.6, f"{v} off", 2.8, anchor="end", fill=THIN)
    sh.text(lx + 4, ly + 11 + n * 4.6,
            f'{len(geo["columns"])} columns · {len(geo["beams"])} beams per level', 2.6, fill=THIN)
    sh.scale_bar(lx + 8, ly + 20 + n * 4.6, fit.k)
    return sh


def power_plan(spec: dict, geo: dict) -> Sheet:
    sh = Sheet(spec, "E2.01", "Power and Lighting Plan — Typical Level", "Electrical")
    fit = Fit(spec)
    sh.title_block(fit.ratio)
    _draw_grid(sh, fit, spec)

    # Building outline for context
    w, d = spec["footprint"]
    sh.rect(fit.x(0), fit.y(d), w * fit.k, d * fit.k, THIN, "none", 0.4)

    for t in geo["trays"]:
        (ax, ay), (bx, by) = t["start"], t["end"]
        sh.line(fit.x(ax), fit.y(ay), fit.x(bx), fit.y(by), "#b8860b", 1.1)
    for dev in geo["terminals"]:
        sh.circle(fit.x(dev["x"]), fit.y(dev["y"]), 1.5, "#1f6f4a", "#e6f3ec", 0.3)
    for dev in geo["sensors"]:
        sh.rect(fit.x(dev["x"]) - 1.1, fit.y(dev["y"]) - 1.1, 2.2, 2.2, "#8b1a1a", "#fbeaea", 0.3)

    _dim_string(sh, fit, spec)
    sh.panel(MARGIN + 4, MARGIN + 4, 148, 14)
    sh.text(MARGIN + 8, MARGIN + 13, "POWER AND LIGHTING PLAN", 5.0, bold=True)
    sh.north_arrow(TB_X - 26, MARGIN + 20)

    legend = [("#b8860b", "rect", f'Cable tray / busway ({len(geo["trays"])})'),
              ("#1f6f4a", "circle", f'Air terminal / diffuser ({len(geo["terminals"])})'),
              ("#8b1a1a", "rect", f'Detection device ({len(geo["sensors"])})')]
    lx, ly = MARGIN + 4, SHEET_H - MARGIN - 52
    sh.panel(lx, ly - 6, 96, 50)
    sh.text(lx + 4, ly, "LEGEND", 3.0, fill=FAINT, bold=True)
    for i, (col, kind, label) in enumerate(legend):
        yy = ly + 7 + i * 5.4
        if kind == "circle":
            sh.circle(lx + 6, yy - 1, 1.5, col, "#fff", 0.3)
        else:
            sh.rect(lx + 4.6, yy - 2.4, 2.8, 2.8, col, "#fff", 0.3)
        sh.text(lx + 11, yy, label, 2.8)
    sh.scale_bar(lx + 8, ly + 34, fit.k)
    return sh


# ─────────────────────────────────────────────────────────────────────────────────────────────────
def build_sheets(spec: dict, geo: dict, model: dict, registers: dict) -> list[tuple[str, str, str]]:
    """Returns [(sheet_number, filename, svg)] for the issued sheets."""
    made = [
        cover_sheet(spec, model, registers),
        floor_plan(spec, geo),
        elevations(spec, geo),
        framing_plan(spec, geo),
        power_plan(spec, geo),
    ]
    out = []
    for sh in made:
        slug = sh.title.replace(" — ", "_").replace(" ", "_").replace(",", "")
        slug = "".join(ch for ch in slug if ch.isalnum() or ch in "._-")
        out.append((sh.number, f"{sh.number}_{slug}.svg", sh.render()))
    return out
